name: beta

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-binary:
    name: Publish the binary to s3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        arch: [amd64, arm64]
    env:
        AWS_REGION: ap-south-1
        GOPRIVATE: github.com/axilock
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0  # Ensure full history and tags are fetched

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-south-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Set Up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.2  # Specify your Go version
    - name: Set Environment Variables
      run: |
        echo "VERSION=$(make version_dev)" >> $GITHUB_ENV
    - name: Build Binary
      run: |
        mkdir -p bin
        git checkout $VERSION
        if [ "${{ matrix.goos }}" = "windows" ]; then
          EXT=".exe"
        else
          EXT=""
        fi
        echo "Building for GOOS=${{ matrix.goos }}, GOARCH=${{ matrix.arch }}"

        export PATH="${GOPATH:-$HOME/go}/bin:$PATH"
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} make dev

        mv bin/axi bin/axi-${{ matrix.goos }}-${{ matrix.arch }}${EXT}
    - name: Upload Binary to S3
      run: |
        if [ "${{ matrix.goos }}" = "windows" ]; then
          EXT=".exe"
        else
          EXT=""
        fi
        # Upload binary under a folder named with the OS-Arch combination.
        aws s3 cp ./bin/axi-${{ matrix.goos }}-${{ matrix.arch }}${EXT} \
          s3://sekrit-releases/dev/$VERSION/${{ matrix.goos }}/${{ matrix.arch }}/axi${EXT}
